import { Router } from "express";
import { alertsRoutes } from "../modules/alerts/alerts.routes.js";
import { auditRoutes } from "../modules/audit/audit.routes.js";
import { authRoutes } from "../modules/auth/auth.routes.js";
import { billingRoutes } from "../modules/billing/billing.routes.js";
import { cashSessionsRoutes } from "../modules/cash/cash.routes.js";
import { exportsRoutes } from "../modules/exports/exports.routes.js";
import { healthRoutes } from "../modules/health/health.routes.js";
import { inventoryRoutes } from "../modules/inventory/inventory.routes.js";
import { pendingCartsRoutes } from "../modules/pending-carts/pending-carts.routes.js";
import { posRoutes } from "../modules/pos/pos.routes.js";
import { productCategoriesRoutes, productsRoutes } from "../modules/products/products.routes.js";
import { purchasesRoutes } from "../modules/purchases/purchases.routes.js";
import { reportsRoutes } from "../modules/reports/reports.routes.js";
import { returnsRoutes } from "../modules/returns/returns.routes.js";
import { rolesRoutes } from "../modules/roles/roles.routes.js";
import { salesRoutes } from "../modules/sales/sales.routes.js";
import { suppliersRoutes } from "../modules/suppliers/suppliers.routes.js";
import { unitsRoutes } from "../modules/units/units.routes.js";
import { usersRoutes } from "../modules/users/users.routes.js";

export const apiRoutes = Router();

apiRoutes.use("/alerts", alertsRoutes);
apiRoutes.use("/audit", auditRoutes);
apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/billing", billingRoutes);
apiRoutes.use("/cash-sessions", cashSessionsRoutes);
apiRoutes.use("/exports", exportsRoutes);
apiRoutes.use("/health", healthRoutes);
apiRoutes.use("/inventory", inventoryRoutes);
apiRoutes.use("/pending-carts", pendingCartsRoutes);
apiRoutes.use("/pos", posRoutes);
apiRoutes.use("/product-categories", productCategoriesRoutes);
apiRoutes.use("/products", productsRoutes);
apiRoutes.use("/purchases", purchasesRoutes);
apiRoutes.use("/reports", reportsRoutes);
apiRoutes.use("/returns", returnsRoutes);
apiRoutes.use("/roles", rolesRoutes);
apiRoutes.use("/sales", salesRoutes);
apiRoutes.use("/suppliers", suppliersRoutes);
apiRoutes.use("/units", unitsRoutes);
apiRoutes.use("/users", usersRoutes);
